[[plugins]]

repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
	autocmd FileType denite call s:denite_my_settings()
	function! s:denite_my_settings() abort
		nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
		nnoremap <silent><buffer><expr> s denite#do_map('do_action', 'split')
		nnoremap <silent><buffer><expr> v denite#do_map('do_action', 'vsplit')
		nnoremap <silent><buffer><expr> t denite#do_map('do_action', 'tabopen')
		nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
		nnoremap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
		nnoremap <silent><buffer><expr> q denite#do_map('quit')
		nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
		nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
	endfunction

	nnoremap <C-p> :Denite file/rec -start-filter<CR>
	nnoremap <Leader>o :Denite outline -start-filter -split=no -filter-split-direction=abo<CR>
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
hook_source = '''
	call ddc#custom#patch_global('sources', ['around', 'nvim-lsp'])
	call ddc#custom#patch_global(
		\ 'sourceOptions',
		\ {
		\ 	'_': {
		\ 		'matchers': ['matcher_head'],
		\ 		'sorters': ['sorter_rank'],
		\ 	},
		\ 	'nvim-lsp': {
		\ 		'mark': 'lsp',
		\ 		'matchers': ['matcher_head'],
		\ 		'forceCompletionPattern': '\.\w*|:\w*|->\w*',
		\ 	},
		\ 	'around': {
		\ 		'mark': 'A'
		\ 	},
		\ })

	call ddc#custom#patch_global(
		\ 'sourceParams',
		\ {
		\ 	'around': {'maxSize': 500},
		\ 	'nvim-lsp': {'kindLabels': {'Class': 'c'}}
		\ })

	" Customize settings on a filetype
	call ddc#custom#patch_filetype(['c', 'cpp'], 'sources', ['around', 'nvim-lsp'])

	" <TAB>: completion.
	inoremap <silent><expr> <TAB>
	\ ddc#map#pum_visible() ? '<C-n>' :
	\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
	\ '<TAB>' : ddc#map#manual_complete()

	" <S-TAB>: completion back.
	inoremap <expr><S-TAB>  ddc#map#pum_visible() ? '<C-p>' : '<C-h>'

	" Use ddc.
	call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
	let g:neosnippet#disable_runtime_snippets = {'_' : 1, 'cpp' : 0}

	imap <C-k> <Plug>(neosnippet_expand_or_jump)
	smap <C-k> <Plug>(neosnippet_expand_or_jump)
	xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_add = '''
	call popup_preview#enable()
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
hook_add = '''
	call signature_help#enable()
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
hook_add = '''
	autocmd User PumCompleteDone call vsnip_integ#on_complete_done(g:pum#completed_item)
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
	\ 'colorscheme' : 'wombat',
	\ 'component_function': {
	\ 	'anzu': 'anzu#search_status'
	\ }
	\ }

	let g:lightline.active = {
	\ 'left' : [
	\	['mode', 'paste'],
	\	['readonly', 'filename', 'modifield', 'anzu'],
	\ ],
	\ }

	let g:lightline.inactive = {
	\ 'left' : [
	\	['readonly', 'filename', 'modified'],
	\ ],
	\ 'right' : [
	\	['lineinfo'],
	\	['percent'],
	\	['fileformat', 'fileencoding', 'filetype'],
	\ ],
	\ }
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
	vmap <Enter> <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
	let g:easy_align_delimiters = {
	\ ']': {
	\     'pattern':       '[\]]',
	\     'left_margin':   0,
	\     'right_margin':  0,
	\     'stick_to_left': 0,
	\   },
	\ ')': {
	\     'pattern':       '[)]',
	\     'left_margin':   0,
	\     'right_margin':  0,
	\     'stick_to_left': 0,
	\   },
	\ }
'''

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = '''
	let g:localvimrc_ask = 0
	let g:localvimrc_sandbox = 0
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
	let g:EasyMotion_do_mapping = 0
	let g:EasyMotion_smartcase = 1
	nmap s <Plug>(easymotion-overwin-f2)
	nmap f <Plug>(easymotion-bd-f)
	nmap <Leader>l <Plug>(easymotion-bd-jk)
'''

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
	nnoremap <C-e> :Vaffle %:h<CR>
'''

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'
hook_add = '''
	let g:win_ime_con_mode = 0
'''

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
	let g:ackprg = 'pt'
'''
