[[plugins]]

repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
	autocmd FileType denite call s:denite_my_settings()
	function! s:denite_my_settings() abort
		nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
		nnoremap <silent><buffer><expr> s denite#do_map('do_action', 'split')
		nnoremap <silent><buffer><expr> v denite#do_map('do_action', 'vsplit')
		nnoremap <silent><buffer><expr> t denite#do_map('do_action', 'tabopen')
	  	nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
	  	nnoremap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
	  	nnoremap <silent><buffer><expr> q denite#do_map('quit')
	  	nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
	  	nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
	endfunction

	nnoremap <C-p> :Denite file/rec -start-filter<CR>
	nnoremap <Leader>o :Denite outline -start-filter -split=no -filter-split-direction=abo<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
	let g:deoplete#enable_at_startup = 1

	call deoplete#custom#option('sources', {
	\	'_': ['buffer'],
	\	'txt': [],
	\	'cpp': ['buffer', 'neosnippet'],
	\})
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
	let g:neosnippet#disable_runtime_snippets = {'_' : 1, 'cpp' : 0}

	imap <C-k> <Plug>(neosnippet_expand_or_jump)
	smap <C-k> <Plug>(neosnippet_expand_or_jump)
	xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
	\ 'colorscheme' : 'wombat',
	\ 'component_function': {
	\ 	'anzu': 'anzu#search_status'
	\ }
	\ }

	let g:lightline.active = {
	\ 'left' : [
	\	['mode', 'paste'],
	\	['readonly', 'filename', 'modified', 'anzu'],
	\ ],
	\ }

	let g:lightline.inactive = {
	\ 'left' : [
	\	['readonly', 'filename', 'modified'],
	\ ],
	\ 'right' : [
	\	['lineinfo'],
	\	['percent'],
	\	['fileformat', 'fileencoding', 'filetype'],
	\ ],
	\ }
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
	vmap <Enter> <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
	let g:easy_align_delimiters = {
	\ ']': {
	\     'pattern':       '[\]]',
	\     'left_margin':   0,
	\     'right_margin':  0,
	\     'stick_to_left': 0,
	\   },
	\ ')': {
	\     'pattern':       '[)]',
	\     'left_margin':   0,
	\     'right_margin':  0,
	\     'stick_to_left': 0,
	\   },
	\ }
'''

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = '''
	let g:localvimrc_ask = 0
	let g:localvimrc_sandbox = 0
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
	let g:EasyMotion_do_mapping = 0
	let g:EasyMotion_smartcase = 1
	nmap s <Plug>(easymotion-overwin-f2)
	nmap f <Plug>(easymotion-bd-f)
	nmap <Leader>l <Plug>(easymotion-bd-jk)
'''

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
	nnoremap <C-e> :Vaffle %:h<CR>
'''

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'
hook_add = '''
	let g:win_ime_con_mode = 0
'''

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
	let g:ackprg = 'pt'
'''
